<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.20" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PropertiesInformation.Core\PropertiesInformation.Core.csproj" />
    <ProjectReference Include="..\PropertiesInformation.Infrastructure\PropertiesInformation.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\" />
    <Folder Include="Payloads\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="DTOs\AuthDtos.cs" />
  </ItemGroup>

</Project>
